### ISSUE TITLE
怎么 模糊查询

### ISSUE THREAD

**Issue by hnsylitao** [ali-sdk/ali-rds#16]
怎么 select、count 方法 模糊查询

**Comment by dickson** [comment]
看源码里没有相关处理，希望能尽早实现。 

p.s. 想知道是否会加入 populate 功能？

**Comment by dickson** [comment]
@hnsylitao https://www.npmjs.com/package/sql-criteria-parser
周末没事写的一个小的转换器，支持一些基本的数据库查询条件(and、or、like..)的转换，可以嵌入到 lib/operator._where 方法中使用。

**Comment by johnnychen** [comment]
同求

**Comment by miaojiuchen** [comment]
同求

**Comment by SimbaZZX** [comment]
害，我拉取代码下来改了一下，加了模糊查询和OR之类的，各位有需要可以用一下试试。
如果有BUG，还得继续改哦，与其吐槽，不如贡献一下 #83
