### ISSUE TITLE
where 空数组问题

### ISSUE THREAD

**Issue by shepherdwind** [ali-sdk/ali-rds#28]
如果 where 是一个空的数组会报错，msyql 语法有问题。感觉这种情况是不是可以直接退出，不查询了。一个空的 where 就返回一个空就行了。

https://github.com/ali-sdk/ali-rds/blob/e4aed300183bd511b9b57412b1e2cd7f5bb0cef8/lib/operator.js#L193

```
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \')\' at line 1'
sqlState: '42000'
index: 0
sql: 'SELECT * FROM `table` WHERE `tableId` IN ()'
```

**Comment by paranoidjk** [comment]
这种还是 fail fast 比较好吧？ 空的数组说明代码逻辑肯定是有问题的，应该早点让开发者察觉？

**Comment by fengmk2** [comment]
呃，value 是空数组，这样传应该不对吧。

**Comment by shepherdwind** [comment]
抛个异常也行，不过直接生成一个错误的 sql 好像不好。

**Comment by shepherdwind** [comment]
异常也还行，这个先关闭吧
