### ISSUE TITLE
mysql 时间格式查询错误

### ISSUE THREAD

**Issue by jakehu** [ali-sdk/ali-rds#47]
数据库格式：2018-03-12 14:46:31
通过egg-mysql查询出来的格式：2018-03-12T06:46:31.000Z
自动加上了时区而且还是错误的时区。
数据库字段类型为`timestamp`

**Comment by nxycdl** [comment]
解决了吗？

**Comment by jakehu** [comment]
@nxycdl 
在`vue`里面定义一个`filter`
```
  let date = new Date(value)
  return format(date, options)
```

**Comment by wtus** [comment]
我也遇到了相同的问题，数据库是 2018-10-10，查出来是 2018-10-09T16:00:00.000Z

**Comment by fengmk2** [comment]
时区……
