### ISSUE TITLE
Async / Await 改造

### ISSUE THREAD

**Issue by XadillaX** [ali-sdk/ali-rds#48]
该库需要将 Generator 改成 Async / Await 改造。

**Comment by LzxHahaha** [comment]
+1

**Comment by kuangshp** [comment]
或者提供转换的方法也可以

**Comment by kuangshp** [comment]
可以使用co模块自己进行包装下
async function query(sql, params=[]) {
    return await co(function *() {
        return yield mysql.query(sql, params);
    })
}

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-rds/pull/103
