### ISSUE TITLE
get 方法不能匹配 null 字段

### ISSUE THREAD

**Issue by sskyy** [ali-sdk/ali-rds#59]
使用 this.app.mysql.get方法时，如果有字段 a 是 null，生成的 sql 代码是：

"SELECT * FROM `page` WHERE `a` = NULL"
这会导致匹配不到正确的数据，需要生成：

"SELECT * FROM `page` WHERE `a` is NULL"

**Comment by fengmk2** [comment]
Duplicate of #35
