### ISSUE TITLE
这库没人维护了吗

### ISSUE THREAD

**Issue by 662** [ali-sdk/ali-rds#77]
kpi产物？

**Comment by hnliyuan** [comment]
咋就没人了呢?  我是egg.js的使用者，我看egg.js的egg-mysql是基于ali-rds做的
但是我看这个库基本上没人维护了， 我还可以放心大胆的用吗？ 
还是去使用sequelize?

**Comment by fengmk2** [comment]
一直在维护，没有 bug 不更新不行吗？
而且它不是 orm，所以跟 sequelize 无法对比。需要 orm 的话请使用 egg-orm，它才是跟 sequelize 对比的模块。

**Comment by qdechochen** [comment]
> 咋就没人了呢? 我是egg.js的使用者，我看egg.js的egg-mysql是基于ali-rds做的
> 但是我看这个库基本上没人维护了， 我还可以放心大胆的用吗？
> 还是去使用sequelize?

太多不自由所以我自己造了个o2sql，有配套的egg-o2sql，可以一试。
