### ISSUE TITLE
db.query对应的原生sql如何打印

### ISSUE THREAD

**Issue by qingfengmy** [ali-sdk/ali-rds#81]
```
let rows = yield db.query('SELECT * FROM your_table WHERE id=:id', { id: 123 });
console.log(rows);
```
如何查看这个sql查询的原生sql，如果sql很复杂，需要获取原生sql查看问题

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-rds/blob/master/lib/client.js#L37 可以覆盖这个方法实现

**Comment by qingfengmy** [comment]
> https://github.com/ali-sdk/ali-rds/blob/master/lib/client.js#L37 可以覆盖这个方法实现

非常感谢！！！
