### ISSUE TITLE
垃圾玩意，KPI产物

### ISSUE THREAD

**Issue by cuijiudai** [ali-sdk/ali-rds#86]
木有文档，各种没法用

**Comment by flftfqwxf** [comment]
确实，文档太简单了，不清楚，是不是功能就做得超级简单，因为用egg-mysql,看到的，结果超级不好用

**Comment by fengmk2** [comment]
有事说事，开源项目，欢迎来贡献。如果继续不友好沟通，我们只好进行屏蔽。

**Comment by cuijiudai** [comment]
我这 issue 都提了一年了，终于想起来看看github了？

**Comment by fengmk2** [comment]
@cuijiudai 我们是开源项目，没有义务去回复你这种不友好的 issue，这是最后一个回复，并且我们会 block 掉。
